/**
 * WISE — shared "What can I ask?" catalog.
 *
 * A single source of truth for the "What can I ask?" side panel across every
 * WISEcodeAI chat surface. Loaded as a classic <script> before any chat mount
 * so it can be fed as the panel's `catalog` (see js/chat-ask.js). Keeping it
 * here means wiseai.html and every other chat show the IDENTICAL rich catalog.
 *
 *   window.WISE_ASK_CATALOG  — { intro, searchPlaceholder, sections:[…] }
 */
(function (global) {
  'use strict';

  global.WISE_ASK_CATALOG = {
      intro: 'A starter catalog of what WISEcodeAI can do today \u2014 organized by what you want to accomplish, with example prompts you can click to use straight into the chat.',
      searchPlaceholder: "Type to filter \u2014 e.g., 'ingredients', 'UPF', 'compare', 'reformulate'",
      sections: [
        {
          id: 'find-foods', title: 'Find foods', icon: 'search',
          desc: 'Search the food corpus by description, barcode, brand, retailer, or category. Start broad and refine; or jump straight to a specific product.',
          items: [
            { title: 'Search foods by description', icon: 'manage_search',
              desc: "Type what you're looking for in plain English \u2014 nutrients, ingredients, brands, retailers, score thresholds \u2014 and WISEai builds the filter for you.",
              prompts: ['High-protein snacks under 200 calories', 'Organic cereals with at least 5 grams of fiber', 'Frozen meals with no artificial colors at Walmart', 'Foods with WISEscore above 70 and Heart Health above 60'],
              tools: ['search_foods_by_description'] },
            { title: 'Look up a product by barcode', icon: 'qr_code_scanner',
              desc: 'Got a UPC? Paste it in and WISEai will find the product, show ingredients, nutrients, and code scores. Works for 8-, 12-, 13-, and 14-digit UPCs.',
              prompts: ['Look up UPC 028400064057', "What's barcode 016000275256?", 'Show me the product with UPC 049000028904'],
              tools: ['find_food_by_upc', 'get_food_id_from_upc'] },
            { title: 'Find a brand', icon: 'sell',
              desc: "Search brands by partial name. Useful when you're not sure how a brand is spelled in the database, or when you want to see how many products a brand has.",
              prompts: ["Find brands containing 'amy'", 'Show me all Kirkland products', "Brands matching 'quest'"],
              tools: ['search_brands'] },
            { title: 'Find a retailer', icon: 'storefront',
              desc: "Retailer names in the database don't always match the spelling you'd expect \u2014 Whole Foods is stored as wholefoods, etc. Use this to find the canonical name before filtering.",
              prompts: ['Is Whole Foods in our database?', "Find retailers matching 'trader'", "Retailers containing 'sprout'"],
              tools: ['search_retailers'] },
            { title: 'Find a product category', icon: 'category',
              desc: 'Categories are compound (e.g., snacks,jerky). Search by keyword to discover the exact category names so your follow-up search hits the right scope.',
              prompts: ['What categories are about snacks?', 'Show me frozen categories', 'Beverage categories with the most products'],
              tools: ['search_categories'] },
            { title: 'See full product details', icon: 'description',
              desc: 'Once you have a food (from search or a UPC lookup), get the full picture \u2014 name, brand, ingredient list, parsed ingredients, nutrients, and every published code score.',
              prompts: ['Show me the full details of this product', "What's in this food, with nutrients and scores?", 'Give me everything about that cereal'],
              tools: ['get_food_details'] },
            { title: 'How big is the database?', icon: 'database',
              desc: 'Get the total food count \u2014 useful as a denominator when you want to know what fraction of the corpus your current filter represents.',
              prompts: ['How many foods are in the database?', "What's the total corpus size?", 'What percentage of foods are these compared to everything?'],
              tools: ['get_total_food_count'] },
            { title: 'Filter by a computed formula or ratio', icon: 'function',
              desc: 'Filter foods by math over their nutrients \u2014 ratios between two nutrients, percent of calories from a nutrient, any computed rule.',
              prompts: ['Find snacks where the zinc to copper ratio is between 10 and 12', 'Find foods where more than 20% of calories come from sugar', 'find me foods in the snack category with their zinc to copper ratio between 10 and 12 and upf minimally processed'],
              tools: ['search_foods_by_description'] },
            { title: 'Exclude foods by ingredient family', icon: 'block',
              desc: 'Exclude foods containing ANY ingredient from a whole family of the canon ontology \u2014 no fruit ingredients, no sweeteners of a kind \u2014 not just a named ingredient.',
              prompts: ['find snack foods with no fruit ingredients in the canon ontology', 'Find cereals with no ingredients from the sweetener category of the canon ontology'],
              tools: ['search_foods_by_description'] },
          ],
        },
        {
          id: 'analyze-set', title: 'Analyze the set', icon: 'analytics',
          desc: 'Once you have a result set, slice it, cross-tab it, look for correlations, or refine the filter surgically. The conversation remembers your filter so you can build incrementally.',
          items: [
            { title: 'Refine your current search', icon: 'tune',
              desc: 'Already have a result set? Make a small change without rebuilding from scratch. Add, remove, or modify any constraint and the filter updates surgically.',
              prompts: ['Add organic to that search', 'Remove the sodium constraint', 'Also exclude artificial colors', 'Sort by protein descending instead'],
              tools: ['amend_food_search'] },
            { title: 'Break the set down by a dimension', icon: 'bar_chart',
              desc: 'Get distributions, breakdowns, cross-tabs, heatmaps. Group by brand, retailer, category, or any published code \u2014 one dimension for a bar chart, two for a heatmap, three for small multiples.',
              prompts: ['Break this down by brand, top 10', 'Create a comparison chart of the top three brands with more than 50 UPCs that are in the top half of the WISE score.', 'Show me UPF distribution across the top 5 retailers', 'Heatmap of UPF by retailer by category', "What's the average sodium per category?"],
              tools: ['analyze_food_distribution'] },
            { title: 'Find statistical relationships between codes', icon: 'hub',
              desc: 'Ask how two code dimensions relate across your set \u2014 how often artificial colors co-occur with ultra-processed, how Clean Label tracks with Heart Health, etc. Returns a contingency table plus an effect-size statistic.',
              prompts: ['How does artificial color presence track with UPF status?', 'Is Clean Label correlated with Heart Health score?', 'Compare emulsifier presence to UPF labels'],
              tools: ['analyze_correlation'] },
            { title: 'Get filter suggestions', icon: 'lightbulb',
              desc: 'Stuck on what to add or improve in your current filter? Ask for suggestions and WISEai will surface relevant criteria you might not have thought of.',
              prompts: ['How could I improve this filter?', 'What other criteria would tighten this set?', 'Suggest some refinements to my search'],
              tools: ['suggest_filter_improvements'] },
            { title: 'Custom visualizations', icon: 'dashboard_customize',
              desc: "Sometimes the default cards aren't quite right. Describe how you want the data shown \u2014 chart type, layout, emphasis \u2014 or prefix with /visualize and WISEai will render a custom HTML report.",
              prompts: ['Show this as a small-multiples grid', '/visualize as a one-page executive report', 'Render this as a heatmap with an insight box at the top'],
              tools: ['render_artifact'] },
            { title: 'Compare two groups defined by a rule', icon: 'compare_arrows',
              desc: 'Split a set of foods by any rule \u2014 a nutrient threshold, a computed formula \u2014 and compare the two groups: averages, medians, counts, score distributions.',
              prompts: ['Compare the average WISEscore of foods where more than 20% of calories come from sugar versus the rest. Give both averages and the counts behind them.', 'Split the foods into those with more than 20% of calories from fat AND more than 20% from sugar, versus the rest. For each group give me the median WISEscore and the percent scoring below 40.', 'Consider only foods that have values for energy, total fat, and total sugar. How many is that? Among them, how many have more than 20% of calories from fat AND more than 20% from sugar? Give me the evaluable count and the count and percent that qualify.'],
              tools: ['analyze_food_distribution'] },
            { title: 'Get one overall number for a set', icon: 'calculate',
              desc: 'Ask for a single statistic over the whole current set \u2014 an average, a median, a percentile \u2014 without any grouping.',
              prompts: ["What's the average WISEscore of those foods?", "What's the median WISEscore of this set?"],
              tools: ['analyze_food_distribution'] },
            { title: 'Rank categories by a rate', icon: 'leaderboard',
              desc: 'For each category (or brand, or retailer), compute the share of foods meeting a rule \u2014 sorted by that share, with small unstable groups excluded.',
              prompts: ['Group those foods by category. For each category, show the count and the percent that meet the rule, sorted by the percent, descending.', "Group by food category and give each category's count and the percent that meets the rule, sorted by percent descending. Only include categories with at least 500 foods so the rates are stable."],
              tools: ['analyze_food_distribution'] },
          ],
        },
        {
          id: 'understand-score', title: 'Understand a score', icon: 'grading',
          desc: 'Score a food against any of the ~50 WISEcode codes, see the step-by-step math, get a plain-English explanation, or look up the algorithm itself.',
          items: [
            { title: 'Score a food against a code', icon: 'scoreboard',
              desc: "Get a code's score for any food \u2014 whether you have a food ID, an ingredient list, or are pasting from a label. WISEai picks the right path automatically.",
              prompts: ['Evaluate this cereal for WISEcode UPF', 'Score this ingredient list against Clean Label', "What's the Heart Health score for that product?"],
              tools: ['evaluate_food_for_code', 'evaluate_ingredients_for_code', 'evaluate_ingredients_for_upf'] },
            { title: 'Explain why a score is what it is', icon: 'psychology',
              desc: 'After scoring, ask WISEai to walk you through the result \u2014 which ingredients pulled the score down, which lifted it, and how each step of the algorithm contributed.',
              prompts: ['Why did this score 7.5?', 'Walk me through why this is ultra-processed', 'Which ingredients hurt the Clean Label score the most?'],
              tools: ['explain_code_result', 'explain_food_score'] },
            { title: 'Get a UPF score breakdown', icon: 'blender',
              desc: 'For ultra-processed-food specifically: get the processing weight, added-sugar contribution, and the classification (Minimally / Lightly / Moderately / Ultra / Super Ultra Processed).',
              prompts: ['Is this product ultra-processed?', 'Give me the UPF breakdown for this', 'Show the processing classification for that food'],
              tools: ['get_upf_score'] },
            { title: 'See how a code is calculated', icon: 'account_tree',
              desc: 'Curious about the algorithm itself? Get the step-by-step recipe for any WISEcode code \u2014 what each step does and how the final score is composed.',
              prompts: ['How is WISEcode UPF calculated?', "What's the recipe for Clean Label?", 'Walk me through how Heart Health is scored'],
              tools: ['get_code_step_recipe'] },
            { title: 'List available codes', icon: 'list_alt',
              desc: 'See the catalog of WISEcode codes you can evaluate against \u2014 their names, descriptions, and version info.',
              prompts: ['What codes are available?', 'List all published codes', 'Show me what versions exist for WISEcode UPF'],
              tools: ['list_code_definitions', 'list_code_versions'] },
          ],
        },
        {
          id: 'improve-food', title: 'Improve a food', icon: 'trending_up',
          desc: 'Get specific, actionable suggestions for making a food score better against a chosen code \u2014 with real replacement ingredients and projected score impact.',
          items: [
            { title: 'Suggest score improvements', icon: 'tips_and_updates',
              desc: 'Tell WISEai what you want to achieve (Clean Label, Non-UPF, higher Heart Health, etc.) and it will suggest specific ingredient swaps and changes with projected score impact.',
              prompts: ['How could this be made Clean Label?', 'Help me get this to Non-UPF status', 'Suggest changes to raise the Heart Health score', 'What would it take to bring the processing score below 5?'],
              tools: ['suggest_code_improvement', 'suggest_improvements'] },
            { title: 'Reparse and re-evaluate with the current parser', icon: 'sync',
              desc: 'When a stored parse looks off, ask WISEai to reparse the ingredient list with the current (or AI) parser and evaluate the fresh result. The original is preserved for side-by-side comparison.',
              prompts: ['Reparse this with the AI parser and see how it scores', 'Try a fresh parse and compare to the original', 'Re-evaluate this with the current parser'],
              tools: ['reparse_and_evaluate_food'] },
          ],
        },
        {
          id: 'what-if', title: 'What-if variations', icon: 'science',
          desc: 'Bring a food into your private workspace, copy it, edit ingredients or nutrients, run all codes, and compare side-by-side. Sandbox reformulation without touching the database.',
          items: [
            { title: 'Bring a food in for experimentation', icon: 'download',
              desc: 'Pull any food from the database into your private workspace and make an editable copy. The original stays untouched as a baseline for comparison.',
              prompts: ['I want to experiment with this product', 'Let me try reformulating this cereal', 'Clone this so I can modify it'],
              tools: ['import_food_to_session', 'clone_food_in_session', 'create_sandbox_session'] },
            { title: 'Remove an ingredient', icon: 'remove_circle_outline',
              desc: 'In your workspace copy, take an ingredient out and watch what happens to the scores. Useful for "what if we just dropped X?" exploration.',
              prompts: ['Remove the BHT from this', 'What if we took out the artificial colors?', 'Drop the high fructose corn syrup'],
              tools: ['remove_ingredient'] },
            { title: 'Change a nutrient value', icon: 'edit',
              desc: 'Adjust any nutrient on your workspace copy \u2014 sodium, added sugar, protein, etc. \u2014 and see how it cascades into the scores.',
              prompts: ['Drop the added sugar to 5 grams', 'What if the sodium were 100 mg?', 'Raise the protein to 12g per serving'],
              tools: ['update_nutrient'] },
            { title: 'Compare original to modified, side-by-side', icon: 'difference',
              desc: 'Run all codes against both versions and see the deltas in one view. The story your reformulation tells.',
              prompts: ['Compare the original to my modified version', 'Show me both versions side by side across all codes', 'What changed in the scores after my edits?'],
              tools: ['compare_foods_in_session'] },
            { title: 'Run all codes against a food', icon: 'apps',
              desc: 'Score a food (original or modified) across every published WISEcode code in one shot. Useful when you want the full picture, not just one score.',
              prompts: ['Score this against all available codes', "Show me every code's result for this food", 'Full code panel for this product'],
              tools: ['calculate_all_codes_in_session', 'calculate_code_score'] },
            { title: "See what's in your workspace", icon: 'folder_open',
              desc: 'List the foods you\u2019ve worked with this session \u2014 originals, clones, and variants \u2014 so you can pick one back up.',
              prompts: ['What foods am I working with right now?', 'List everything in my workspace', "Show me the foods I've evaluated this session"],
              tools: ['workspace_list_foods', 'workspace_get_food', 'list_foods_in_session'] },
            { title: 'Commit accumulated changes', icon: 'save',
              desc: 'When your reformulation is ready, apply the changes to lock in a new ingredient list and updated nutrients. The food is reparsed and ready for full evaluation.',
              prompts: ['Apply these changes to my reformulation', 'Update the ingredient list to the new version', 'Save these changes and reparse'],
              tools: ['apply_food_changes'] },
            { title: 'Create a custom food', icon: 'add_box',
              desc: 'Create a brand-new food from an ingredient list, or clone an existing food into an editable copy - right in your current database. Edit it and re-evaluate as you iterate.',
              prompts: ['Create a custom food from this ingredient list: cultured skim milk, blueberries, chia seeds, fruit pectin, live active yogurt cultures', 'Clone this food so I can edit it', 'Remove the cane sugar from my custom food and re-evaluate it'],
              tools: ['evaluate_ingredients_for_code', 'clone_food', 'apply_food_changes'] },
          ],
        },
        {
          id: 'explore-ingredients', title: 'Explore ingredients', icon: 'biotech',
          desc: 'Dive into the ~10,000-entry canon ingredient database \u2014 search, classify, look up specific terms, and pull distributions across categories, processing levels, GRAS status, allergens, and more.',
          items: [
            { title: 'Search ingredients by description', icon: 'manage_search',
              desc: 'Find canon ingredients matching any natural-language description \u2014 by category, GRAS status, processing level, allergen profile, dietary flags, etc.',
              prompts: ['Find me all the emulsifiers', 'Show me GRAS sweeteners', 'Ingredients with processing level above 3', 'Artificial color additives'],
              tools: ['search_canon_ingredients', 'search_canon_ingredients_full', 'search_ingredients'] },
            { title: 'Look up a specific ingredient term', icon: 'search',
              desc: 'Resolve an exact label term \u2014 including abbreviations and aliases (BHA, BHT, ADA, etc.) \u2014 to its canon entry. Returns GRAS status, processing level, category, and more.',
              prompts: ['What is BHA?', 'Tell me about azodicarbonamide', 'Look up BHA, BHT, and TBHQ'],
              tools: ['lookup_canon_ingredient_by_terms', 'get_ingredient_details'] },
            { title: 'Analyze ingredient distributions', icon: 'bar_chart',
              desc: 'Get breakdowns and cross-tabs across the canon catalog \u2014 by category, processing level, GRAS status, allergen, and more. Same patterns as food distribution analysis, but over the ingredient world.',
              prompts: ['Break down ingredients by category', 'GRAS status by processing level', 'Distribution of sweeteners by category', 'Heatmap of category by processed level'],
              tools: ['analyze_canon_ingredients', 'analyze_canon_ingredient_distribution'] },
            { title: 'Parse a raw ingredient list', icon: 'segment',
              desc: 'Paste an ingredient list from a label and get every ingredient resolved to its canon entry \u2014 with processing level, GRAS, category, allergen info, dietary flags. No scoring, just classification.',
              prompts: ['Parse this ingredient list and tell me about each one', "What's in this label? [paste ingredients]", 'Classify these ingredients with canon data'],
              tools: ['parse_ingredient_list'] },
            { title: 'See what you can ask about ingredients', icon: 'schema',
              desc: 'Get the catalog of attributes and distinct values in the canon ingredient database \u2014 useful when you want to know what columns and values are queryable.',
              prompts: ['What attributes does the ingredient database have?', 'Show me the ingredient schema', 'What can I query on canon ingredients?'],
              tools: ['get_canon_ingredient_schema', 'get_nutrient_catalog'] },
          ],
        },
        {
          id: 'stats-modeling', title: 'Statistics & modeling', icon: 'query_stats',
          desc: 'Go beyond counts and cross-tabs: fit predictive models, quantify effect sizes, map co-occurrence and ingredient enrichment, summarize distributions, and assemble the whole analysis into a formal report. The heavier statistical and machine-learning tools live here.',
          items: [
            { title: 'Predict a property with a trained model', icon: 'model_training',
              desc: 'Fit a classifier that predicts whether a food has a property (for example, contains a given additive) from the rest of its ingredients, then read how well it separates the two groups and which features drive it. Logistic regression and random forest, scored on held-out foods.',
              prompts: ['How well can you predict whether a food contains BHT just from the rest of its ingredient list?', 'Build a model that tells apart foods that contain ADA from those that do not, and tell me how accurate it is.', 'Fit both a logistic-regression and a random-forest model for TBHQ and compare how well each separates the two groups.', 'For BHA, show the ingredients that most raise and most lower the odds that a food also contains it, ranked by strength.', 'Assess how predictable each of BHA, BHT, TBHQ, and ADA is from the rest of the ingredient list. Fit a logistic-regression and a random-forest classifier per additive (excluding the other three as features), report the area under the curve for each, and show the signed logistic coefficients and the random-forest importances per additive.'],
              tools: ['fit_predictive_model'] },
            { title: 'Co-occurrence and ingredient enrichment', icon: 'grain',
              desc: 'See which ingredients or additives travel together, how likely one is given another, and which ingredients are over-represented around a target far above their baseline rate. Co-occurrence counts, conditional probabilities, similarity, and lift.',
              prompts: ['How often do BHA, BHT, TBHQ, and ADA show up together in the same product?', 'Which pairs of these four additives appear together most often?', 'For BHA, BHT, TBHQ, and ADA, show the probability of finding one of them given that another is present.', 'For each of BHA, BHT, TBHQ, and ADA, find the ingredients that appear alongside it far more than their baseline rate across all packaged foods, and present the enrichment as an ingredient-by-additive figure.'],
              tools: ['analyze_food_distribution'] },
            { title: 'Effect-size contrasts between groups', icon: 'straighten',
              desc: 'Compare two groups of foods on a nutrient or metric and express the gap as a standardized effect size, so differences measured on very different scales become directly comparable. With-versus-without contrasts using a pooled standard deviation.',
              prompts: ['Do foods with TBHQ tend to be higher or lower in calories, fat, and sodium than foods without it?', 'Compare the average and the spread of sodium between foods that contain ADA and those that do not.', 'Compare the nutrition profiles of foods that contain BHA, BHT, TBHQ, or ADA against foods that do not, using a standardized effect size so the nutrients are comparable on one scale.'],
              tools: ['analyze_food_distribution'] },
            { title: 'Distribution shape, percentiles, and spread', icon: 'ssid_chart',
              desc: 'Summarize how a nutrient or metric is distributed across a set: medians, quartiles, upper percentiles, means, and standard deviations, broken down by any dimension you choose.',
              prompts: ['For foods containing TBHQ, show the median and the 25th, 75th, and 90th percentiles of sodium.', 'Break down the average and the standard deviation of sugar by whether a food contains BHT.', 'Show how calories are distributed across retailers for foods with a synthetic antioxidant, with medians and quartiles.'],
              tools: ['analyze_food_distribution'] },
            { title: 'Build a formal scientific report', icon: 'article',
              desc: 'Assemble an entire multi-section analysis into a formal, published-style document with figures, tables, and short methods notes. Good for a full dossier on a set of additives, a deep dive on a single category, or reproducing an outside report on our own catalog.',
              prompts: ['Write a short formal report on how common BHT is across packaged foods, with one chart and a takeaway.', 'Write a formal report on additive use within breakfast cereals: prevalence, which additives concentrate there, and how their presence tracks with nutrition, with figures and short methods notes.', 'Put together a formal, published-style report on the synthetic antioxidants and bleaching agents BHA, BHT, TBHQ, and ADA across packaged foods: how common each is, which categories they concentrate in, how they co-occur, what ingredients cluster around each, how their nutrition compares to foods without them, and how predictable each is from the ingredient list. Sections, figures, and methods notes throughout.', 'I have a published analysis of preservatives in packaged foods; reproduce the same figures and tables on our catalog as a formal report.'],
              tools: ['compose_report', 'fit_predictive_model', 'analyze_food_distribution', 'analyze_correlation'] },
            { title: 'Run a code against a food set or all foods', icon: 'playlist_add_check',
              desc: 'Run any code - including one you just built - against a whole food set or the entire food universe in one operation. You get the score DISTRIBUTION back: count, mean, median, spread, percentiles, and a histogram, with an interpretation.',
              prompts: ['Run the Fat Quality Score against the Poor Carb Quality food set', 'Run my new code against all foods and interpret the score distribution', "Compare my code's score distribution between the Poor Carb Quality and Poor Protein Quality sets"],
              tools: ['calculate_codes'] },
          ],
        },
        {
          id: 'literature', title: 'Scientific literature & evidence', icon: 'menu_book',
          desc: 'Ground decisions in peer-reviewed research. Ask whether an additive is a health concern, weigh a reformulation against the evidence, check whether a marketing claim is defensible, or get the science behind an ingredient. The assistant searches the peer-reviewed scientific literature and answers with cited studies, not opinion.',
          items: [
            { title: 'Check whether an ingredient is a health concern', icon: 'health_and_safety',
              desc: 'Ask whether an additive, preservative, sweetener, or oil is something to worry about and get an answer grounded in peer-reviewed toxicology and health studies, with the strength of the evidence and citations, instead of an opinion.',
              prompts: ["Should I be worried about BHA in my kid's cereal?", 'Is titanium dioxide in food actually harmful?', 'How strong is the evidence that TBHQ causes health problems?', 'What does the research say about the health effects of synthetic antioxidants like BHA, BHT, and TBHQ, and how consistent are the findings?'],
              tools: ['search_scientific_literature'] },
            { title: 'Weigh a reformulation or ingredient swap against the evidence', icon: 'balance',
              desc: 'Bring the research to a product decision: whether removing an additive is worth it, what to replace an ingredient with, or which of two ingredients is the healthier choice, answered from the evidence rather than gut feel.',
              prompts: ["We're thinking of pulling TBHQ from our snacks. Is it worth it?", "What's the healthiest oil to cook with?", 'Is palm oil actually unhealthy, or is that a myth?', 'Based on the evidence, what should we replace high-fructose corn syrup with?'],
              tools: ['search_scientific_literature'] },
            { title: 'Substantiate a health or marketing claim', icon: 'verified',
              desc: 'Before a claim goes on a package, check whether the science supports it. Ask whether a claim such as gut-friendly or heart-healthy is defensible for a given ingredient or fat profile, and see the supporting or contradicting studies.',
              prompts: ['Can we call this product gut-friendly?', 'Is a heart-healthy claim defensible for this fat profile?', 'Does adding omega-3 justify a health claim on the label?'],
              tools: ['search_scientific_literature'] },
            { title: 'Understand the science behind a concern', icon: 'quiz',
              desc: 'Get the why behind a food-health topic: the mechanism, the current state of evidence, or why an ingredient is getting attention, summarized from the peer-reviewed literature with citations.',
              prompts: ['Why are emulsifiers getting a bad reputation lately?', 'Why do people say seed oils are bad?', 'According to the research, how does aspartame affect the body?'],
              tools: ['search_scientific_literature'] },
            { title: 'Ground a score or definition in the evidence', icon: 'rule',
              desc: 'When defining what better-for-you, ultra-processed, or fat quality should mean, base the dimensions on the nutrient-profiling and nutrition-science literature rather than intuition. The assistant pulls the evidence and distills the most defensible criteria.',
              prompts: ['Design a better-for-you score for our beverages.', 'Based on the science, what dimensions should a processing-level score include?', 'Help me build a scientific definition of fat quality for packaged foods from the literature.'],
              tools: ['search_scientific_literature'] },
          ],
        },
        {
          id: 'custom-scores', title: 'Build custom scores', icon: 'construction',
          desc: 'Design your own scoring algorithm in conversation: describe the concept in plain English, strengthen it with peer-reviewed research, build it into a runnable code, and evaluate real foods against it.',
          items: [
            { title: 'Build a code from a concept', icon: 'build',
              desc: 'Describe the score you want in one sentence. WISEai decomposes it into concepts, can strengthen them with peer-reviewed literature (original, research, and blended options), and builds the runnable code.',
              prompts: ['Describe the algorithm of this new code', 'Strengthen it with peer-reviewed research first', 'Build a corrected v2 of this code', 'Build a fat quality score, 0 to 100, that rewards olive oil, nuts, and seeds in the leading ingredients and penalizes palm oil and partially hydrogenated oils.'],
              tools: ['codebuilder_decompose_concept', 'codebuilder_expand_code_concept_with_research', 'codebuilder_build_code'] },
            { title: 'Evaluate foods against your code', icon: 'fact_check',
              desc: 'Run a code you are still developing against any food you can see, with a step-by-step breakdown of how the algorithm scored it.',
              prompts: ['Evaluate this food against the code we just built', 'What codes do I have in development?'],
              tools: ['evaluate_food_for_code', 'list_codes_in_development'] },
          ],
        },
        {
          id: 'sets-favorites', title: 'Food sets & favorites', icon: 'bookmark',
          desc: 'Curate collections you can come back to: food sets materialized from any search (the full result set or a top-N), and favorite foods - personal or shared with your organization.',
          items: [
            { title: 'Create a food set from a search', icon: 'playlist_add',
              desc: 'Turn any search into a named FOOD SET in one statement - the FULL result set, not just the visible top rows, or the top N by your sort. Refill it any time; the set keeps its identity.',
              prompts: ['Create a food set called Poor Carb Quality from all foods with a Poor carbohydrate quality label', 'Put the top 1000 foods by WISEscore into a food set called Top Scorers', 'Refresh the Poor Carb Quality set from that same search'],
              tools: ['fill_food_set_from_filter'] },
            { title: 'List and curate food sets', icon: 'list',
              desc: 'See the food sets available in your current database and add individual foods to a set by hand.',
              prompts: ['What food sets do I have?', 'Add this food to my Demo Candidates set'],
              tools: ['list_food_sets', 'add_foods_to_food_set'] },
            { title: 'Favorite foods', icon: 'favorite',
              desc: 'Keep foods at your fingertips. Favorites are personal by default, can be shared with your organization, and can be pinned to a specific code with a note saying why.',
              prompts: ['Add this yogurt to my favorites', 'What are my favorite foods?', 'Remove it from my favorites', 'Favorite this food for the whole organization', 'Favorite this food for my Fat Quality Score with a note that it is a strong counter-example'],
              tools: ['add_favorite_food', 'list_favorite_foods', 'remove_favorite_food'] },
          ],
        },
        {
          id: 'fda-regulatory', title: 'FDA & regulatory records', icon: 'gavel',
          desc: 'Official government records about food substances and policy: FDA and HHS announcements and events, per-substance regulatory status, and GRAS filings.',
          items: [
            { title: 'Find FDA & HHS announcements, meetings, and events', icon: 'campaign',
              desc: 'Search a daily-updated store of FDA and HHS newsroom items: press releases, recall announcements, outbreak advisories, safety alerts, and meeting or event announcements \u2014 the things the Federal Register never carries.',
              prompts: ['Are there any upcoming FDA or HHS meetings about food policy?', 'What has the FDA announced recently about food dyes?', 'Did HHS put out a press release about GRAS reform this year?'],
              tools: ['search_hhs_fda_news'] },
            { title: "Check FDA's regulatory status of a substance", icon: 'policy',
              desc: 'Look up FDA\u2019s official record for an ingredient in one step: where it is authorized in the CFR, what technical effects it is listed for, and what the historical SCOGS safety review concluded \u2014 including when a substance is NOT listed, which is itself an answer.',
              prompts: ["What is FDA's status for BHT?", 'Is azodicarbonamide an approved food additive in the US?', 'What did the SCOGS review conclude about BHA, and has FDA revisited it since?'],
              tools: ['lookup_food_substance_status'] },
            { title: "Look up GRAS notice filings and FDA's responses", icon: 'assignment',
              desc: 'See who has notified FDA that a substance is Generally Recognized As Safe: each filing\u2019s notifier, intended use, filing date, and FDA\u2019s response letter ("no questions" or "ceased to evaluate").',
              prompts: ['Has anyone filed a GRAS notice for monk fruit extract?', 'Who told FDA that steviol glycosides are GRAS, and what did FDA respond?'],
              tools: ['lookup_food_substance_status'] },
            { title: 'Search FDA food recalls', icon: 'report',
              desc: "Search the FDA's official recall and enforcement records: what was recalled, by which firm, why, how serious (Class I-III), and where it was distributed.",
              prompts: ['Have there been any recalls involving cinnamon?', "Show me this year's Class I food recalls", 'Which firms recalled products for undeclared milk, and which states were affected?'],
              tools: ['search_fda_food_recalls'] },
            { title: 'Search FDA adverse-event reports for foods & supplements', icon: 'sick',
              desc: 'Search consumer- and provider-reported illnesses and reactions tied to foods and dietary supplements. These are spontaneous reports \u2014 associations, not proven causation.',
              prompts: ['What adverse events have been reported for kratom supplements?', 'What are the most commonly reported reactions for energy drinks?'],
              tools: ['search_fda_food_adverse_events'] },
            { title: 'Read the law itself: the regulation and the statute', icon: 'menu_book',
              desc: 'Read the actual text of any federal food regulation (21 CFR) as it stands today, or as it stood on a past date, plus the statute underneath it (the FD&C Act, 21 USC). Answers quote the official eCFR and GovInfo sources, public domain, with the official links. You get the regulation itself, not a summary of it.',
              prompts: ['What does 21 CFR 172.185 say?', 'Pull the CFR text for azodicarbonamide', 'What is the statutory definition of a food additive?', 'What law authorizes FDA to regulate food additives, and where is the Delaney Clause?', 'What did 21 CFR 172.185 say as of January 2017?'],
              tools: ['lookup_cfr_regulation', 'lookup_us_code'] },
            { title: 'Trace how a regulation changed and why', icon: 'history',
              desc: "Search the Federal Register, the daily official journal where every rule, proposed rule, and notice is published. Find the rulemaking behind an ingredient or a CFR part, filter final rules from proposals from notices, and reconstruct how today's regulation came to say what it says: the petitions, the amendments, and their dates.",
              prompts: ['Find Federal Register documents about azodicarbonamide', 'What is the rulemaking history on partially hydrogenated oils and trans fat?', 'Show me Federal Register rulemaking touching 21 CFR part 172', 'How did 21 CFR 172.185 change over time?'],
              tools: ['search_federal_register'] },
            { title: 'Follow the public docket and its comments', icon: 'forum',
              desc: 'The Federal Register announces a regulatory action; Regulations.gov is where it actually happens. Search dockets and filed documents, open a docket to see everything in it (notices, supporting materials, extensions) with comment-period status and how many public comments each document has drawn. The "what happened next?" tool for any rulemaking.',
              prompts: ['Is there a docket on the BHT request for information?', 'Open the BHT docket: what has been filed, and how many public comments are in?', 'What food-related documents were posted to Regulations.gov this month?', 'Find the Federal Register notice on the BHT reassessment and tell me what happened next in its docket'],
              tools: ['search_regulations_gov', 'get_regulations_gov_docket'] },
            { title: 'Compare US and EU treatment of an ingredient', icon: 'public',
              desc: 'Resolve any EU act to its official title and EUR-Lex link (Regulation 1333/2008 and its Union list of authorised additives, E-numbers), and set it against the US position in 21 CFR. Where the jurisdictions diverge (an additive permitted here and unauthorised there), the divergence is the headline, cited to both jurisdictions\u2019 primary law.',
              prompts: ['Is BHT (E321) permitted in the EU, and what about azodicarbonamide?', 'What does EU Regulation 1333/2008 say about food additives?', 'Compare how the US and EU treat BHA and BHT'],
              tools: ['lookup_eu_regulation', 'lookup_cfr_regulation'] },
            { title: 'Run a full regulatory investigation', icon: 'travel_explore',
              desc: 'One question, the whole pipeline: WISEai chains the trade press, the OIRA review pipeline, agency news, the Federal Register, the public docket, FDA\u2019s inventories, enforcement records, and the codified law into a single investigation: placing a rule on its timeline or building a complete regulatory and safety profile of an ingredient, each claim cited to the channel that carries it.',
              prompts: ['Where does the GRAS self-affirmation overhaul actually stand?', 'Give me the complete regulatory and safety picture for azodicarbonamide', 'Walk me through the TBHQ regulation, how it changed, and the law it rests on', "We're weighing whether to pull BHA from our formulations. Make the case."],
              tools: ['search_trade_press', 'search_oira_reviews', 'search_hhs_fda_news', 'search_federal_register', 'search_regulations_gov', 'get_regulations_gov_docket', 'lookup_food_substance_status', 'lookup_cfr_regulation', 'lookup_us_code', 'lookup_eu_regulation', 'search_fda_food_recalls', 'search_fda_food_adverse_events'] },
          ],
        },
        {
          id: 'retailers', title: 'Retailers & private label', icon: 'storefront',
          desc: 'Curated knowledge about US food retail: who owns which banners, each retailer\u2019s own-brand portfolio, and how well those store brands are represented in the data.',
          items: [
            { title: 'See who owns a retailer', icon: 'account_balance',
              desc: 'The curated map of US food retail ownership: which parent conglomerate owns a banner, which banners a company operates, industry rankings, and ownership history \u2014 research-sourced with citations.',
              prompts: ['Who owns King Soopers?', 'Which banners belong to Albertsons?', 'How do the major grocery conglomerates rank by sales?'],
              tools: ['lookup_retailers'] },
            { title: "List a retailer's private-label brands", icon: 'inventory_2',
              desc: 'The curated own-brand portfolio of a retailer or conglomerate: which brands are store brands, their tier (value / core / premium), and the exact spellings they appear under in the data.',
              prompts: ["What are Kroger's private label brands?", 'Is Great Value a store brand, and whose is it?', "Which of Albertsons' own brands are premium tier?"],
              tools: ['lookup_retailer_private_label_brands'] },
            { title: "Check how well a retailer's private label is covered in the data", icon: 'fact_check',
              desc: "Data quality check: compares the products we actually hold for a retailer's own brands against the curated portfolio, so a report can say which store brands are well-represented, thin, or missing.",
              prompts: ["How well is Walmart's private label represented in our data?", 'Which Kroger store brands are thin or missing in the catalog?'],
              tools: ['analyze_retailer_private_label_brand_coverage'] },
          ],
        },
      ],
  };
})(typeof window !== 'undefined' ? window : this);
