#!/usr/bin/env python3
"""Scan the repo for codebase size stats.

Counts lines of code by file type (HTML / JS / CSS / Python) and the number
of HTML pages — both for the working tree ("now") and for one snapshot per
day of git history (so the UI can show an up/down trend). Feeds the
Codebase score cards on pages/all-modules.html.

Regenerate with:
  python3 scripts/scan_code_stats.py
"""
import json
import os
import subprocess
from datetime import date

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# The file types that count as "code" here.
EXTS = ("html", "js", "css", "py")

# Auto-generated data blobs — big machine-written files that would distort a
# hand-written-code count (this scanner's own output included).
SKIP_FILES = {"icon-inventory-data.js", "code-stats-data.js", "gs-data.js"}

# Directories never worth scanning in the working tree.
SKIP_DIRS = {".git", "node_modules", "__pycache__"}


def ext_of(path):
    ext = path.rsplit(".", 1)[-1].lower()
    return ext if ext in EXTS else None


def skipped(path):
    return os.path.basename(path) in SKIP_FILES


def scan_working_tree():
    """Line + file counts for the repo as it is right now (uncommitted included)."""
    lines = {e: 0 for e in EXTS}
    files = {e: 0 for e in EXTS}
    for dirpath, dirs, names in os.walk(ROOT):
        dirs[:] = [d for d in dirs if d not in SKIP_DIRS and not d.startswith(".")]
        for name in names:
            ext = ext_of(name)
            if not ext or name in SKIP_FILES:
                continue
            path = os.path.join(dirpath, name)
            try:
                with open(path, "r", encoding="utf-8", errors="ignore") as fh:
                    n = sum(1 for _ in fh)
            except Exception:
                continue
            lines[ext] += n
            files[ext] += 1
    return lines, files


def git(*args):
    return subprocess.run(
        ["git", *args], cwd=ROOT, capture_output=True, text=True, check=False
    ).stdout


def daily_snapshot_commits():
    """The newest commit of each day, oldest day first: [(date, sha), …]."""
    out = git("log", "--format=%H %cd", "--date=short")
    seen = set()
    snaps = []
    for line in out.splitlines():
        sha, day = line.split()
        if day in seen:
            continue
        seen.add(day)
        snaps.append((day, sha))
    snaps.reverse()
    return snaps


def counts_at(sha):
    """Per-extension line counts + HTML page count at one commit, via
    `git grep -c` (a line count per tracked file, no checkout needed)."""
    pathspecs = ["*." + e for e in EXTS]
    out = git("grep", "-I", "-c", "-e", "", sha, "--", *pathspecs)
    lines = {e: 0 for e in EXTS}
    pages = 0
    for row in out.splitlines():
        # <sha>:<path>:<count>
        try:
            _sha, rest = row.split(":", 1)
            path, count = rest.rsplit(":", 1)
        except ValueError:
            continue
        ext = ext_of(path)
        if not ext or skipped(path):
            continue
        lines[ext] += int(count)
        if ext == "html":
            pages += 1
    return lines, pages


def main():
    now_lines, now_files = scan_working_tree()

    series = []
    for day, sha in daily_snapshot_commits():
        lines, pages = counts_at(sha)
        series.append(
            {
                "date": day,
                "total": sum(lines.values()),
                "html": lines["html"],
                "js": lines["js"],
                "css": lines["css"],
                "py": lines["py"],
                "pages": pages,
            }
        )

    out = {
        "generatedAt": date.today().isoformat(),
        "now": {
            "total": sum(now_lines.values()),
            "html": now_lines["html"],
            "js": now_lines["js"],
            "css": now_lines["css"],
            "py": now_lines["py"],
            "pages": now_files["html"],
            "files": sum(now_files.values()),
        },
        "series": series,
    }

    json_path = os.path.join(ROOT, "scripts", "code-stats.json")
    with open(json_path, "w", encoding="utf-8") as fh:
        json.dump(out, fh, indent=2)

    # An ES module the Codebase score cards can import directly (no fetch,
    # works from file:// and the dev server alike) — same pattern as the
    # Icon Inventory data.
    js_path = os.path.join(ROOT, "js", "code-stats-data.js")
    header = (
        "/* AUTO-GENERATED by scripts/scan_code_stats.py — do not edit by hand.\n"
        " * Lines of code by file type (HTML/JS/CSS/Python) + the HTML page count,\n"
        " * for the working tree now and one git snapshot per day (the trend).\n"
        " * Generated data blobs are excluded. Regenerate with:\n"
        " *   python3 scripts/scan_code_stats.py\n"
        " */\n"
    )
    with open(js_path, "w", encoding="utf-8") as fh:
        fh.write(header)
        fh.write("export const CODE_STATS = ")
        json.dump(out, fh, indent=2, ensure_ascii=False)
        fh.write(";\n")

    print("now:", out["now"])
    print("snapshots:", len(series))
    print("wrote:", os.path.relpath(json_path, ROOT))
    print("wrote:", os.path.relpath(js_path, ROOT))


if __name__ == "__main__":
    main()
